export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST';
export const COMPANY_LIST_REQUEST_SUCCESS = 'COMPANY_LIST_REQUEST_SUCCESS';
export const COMPANY_LIST_REQUEST_ERROR = 'COMPANY_LIST_REQUEST_ERROR';

export const COMPANY_CREATE = 'COMPANY_CREATE';
export const COMPANY_CREATE_SUCCESS = 'COMPANY_CREATE_SUCCESS';
export const COMPANY_CREATE_ERROR = 'COMPANY_CREATE_ERROR';

export const COMPANY_UPDATE = 'COMPANY_UPDATE';
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS';
export const COMPANY_UPDATE_ERROR = 'COMPANY_UPDATE_ERROR';

export const COMPANY_DELETE = 'COMPANY_DELETE';
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_ERROR = 'COMPANY_DELETE_ERROR';
