export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_REQUEST_SUCCESS = 'SERVICE_LIST_REQUEST_SUCCESS';
export const SERVICE_LIST_REQUEST_ERROR = 'SERVICE_LIST_REQUEST_ERROR';

export const SERVICE_CREATE = 'SERVICE_CREATE';
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS';
export const SERVICE_CREATE_ERROR = 'SERVICE_CREATE_ERROR';

export const SERVICE_UPDATE = 'SERVICE_UPDATE';
export const SERVICE_UPDATE_SUCCESS = 'SERVICE_UPDATE_SUCCESS';
export const SERVICE_UPDATE_ERROR = 'SERVICE_UPDATE_ERROR';

export const SERVICE_DELETE = 'SERVICE_DELETE';
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';
export const SERVICE_DELETE_ERROR = 'SERVICE_DELETE_ERROR';
